class UsersController < ApplicationController
  
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	#get params from a hash of hashes generated by the form on signup page. Note on failure, old values are saved
  	@user = User.new(params[:user])
  	if @user.save
  		#handle successful save
  		sign_in @user
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_to @user
  	else
  		#flash.now[:error] = "Oops, can you try signing up again?"
  		render 'new'
  	end

  end
end
