class UsersController < ApplicationController
  # only allow updating user values if you're signed in already
   before_filter :signed_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
   before_filter :correct_user, only: [:edit, :update]
   before_filter :admin_user, only: :destroy
   before_filter :unsigned_user, only: [:new, :create]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page] )
  end

  def new
  	@user = User.new
  end

  def create
  	#get params from a hash of hashes generated by the form on signup page. Note on failure, old values are saved
  	@user = User.new(params[:user])
  	if @user.save
  		#handle successful save
  		sign_in @user
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_to @user
  	else
  		#flash.now[:error] = "Oops, can you try signing up again?"
  		render 'new'
  	end

  end

  def edit
   # @user = User.find(params[:id]) remove this line because user variable should be detected via cookie.
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])

    if current_user.admin? && !current_user?(@user)
      User.find(params[:id]).destroy
      flash[:success] = "User destroyed"
      redirect_to users_path
    else
      flash[:error] = "Hey, no need to destroy yourself!"
      redirect_to users_path
    end
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def unsigned_user
      if signed_in?
        redirect_to root_path, notice: "You're signed in already! No need for another account."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end

end
