class UsersController < ApplicationController
  # only allow updating user values if you're signed in already
   before_filter :signed_in_user, only: [:index, :edit, :update]
   before_filter :correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	#get params from a hash of hashes generated by the form on signup page. Note on failure, old values are saved
  	@user = User.new(params[:user])
  	if @user.save
  		#handle successful save
  		sign_in @user
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_to @user
  	else
  		#flash.now[:error] = "Oops, can you try signing up again?"
  		render 'new'
  	end

  end

  def edit
   # @user = User.find(params[:id]) remove this line because user variable should be detected via cookie.
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def signed_in_user

      unless signed_in?
        store_location
        redirect_to signin_path, notice: "Please sign in."
      end
      # notice condensed versoin of = flash[:notice] ="Please Sign in"
      # redirect_to signin_path. Works for error key, but not for success.
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

end
